import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import styles1 from "../styles/Home1.module.css";
import styles2 from "../styles/Home2.module.css";
// import Script from "next/script";

export default function Home() {

  // console.log(styles)
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords " content="Next js ,Hunting Coder0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnLoad'></Script> */}
      <div>
        <nav className={styles.mainNav}>
          <ul>
            <Link href="/">
              <a><li>Home</li></a>
            </Link>
            <Link href="/about">
              <a><li>About</li></a>
            </Link>
            <Link href="/blog">
              <a><li>Blog</li></a>
            </Link>
            <Link href="/contact">
              <a><li>Contact</li></a>
            </Link>
          </ul>
        </nav>
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        {/* <div className={`${styles2.con} ${styles1.con}`}> */}
        {/* <div className={`${styles1.con}`}> */}
        <div className={`${styles2.con} `}>
          <h2>Popular Blogs</h2>
          <div className="blog">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
