import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import styles2 from "../styles/Home2.module.css";
// import styles1 from "../styles/Home1.module.css";
// import Script from "next/script";
import Dummy from "../components/dummy";

export default function Home() {
  // console.log(styles)
  return (
    <div className={styles.container}>
      <Dummy />
      <style jsx>
        {
          /* {`
          .mySpan {
            color: blue;
          }
        `} */
          `
            .h2 {
              font-size: 39 px;
            }
          `
        }
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords " content="Next js ,Hunting Coder0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnLoad'></Script> */}
    
      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* <span className="mySpan dummy ">Hunting Coder</span> */}
          <span className="mySpan">Hunting Coder</span>
        </h1>
        <div className={styles.imgWrap}>
          <Image
            className="myImg"
            src="/homeImg.avif"
            alt=""
            width={237}
            height={158}
          />
        </div>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        {/* <div className={`${styles2.con} ${styles1.con}`}> */}
        {/* <div className={`${styles1.con}`}> */}
        {/* <div className={`${styles2.con} `}> */}
        <div>
          <h2>Popular Blogs</h2>
          <div className="blog">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>
          <div className="blog">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>
          <div className="blog">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>
          <div className="blog">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>
        </div>
      </main>
    </div>
  );
}
